apiVersion: batch/v1
kind: Job
metadata:
  name: ngrok
spec:
  template:
    spec:
      containers:
      - name: ngrok
        image: wernight/ngrok
        args:
        - "ngrok"
        - "http"
        - "3000"
        env:
        - name: NGROK_AUTHTOKEN
          value: "2uKOGSVlCWXsauHYoXH6PISFCyp_7GxUKg6uPKQGy3eNUUEha"
      restartPolicy: Never

